{% set name = "path.py" %}
{% set version = "11.4.0" %}
{% set checksum = "c79263d5989b547eb18a7cd189fc77f44e9291d0b7921177f44f45b2ee99a688" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools_scm >=1.15.0

  run:
    - python

test:
  imports:
    - path

about:
  home: https://github.com/jaraco/path.py
  license: MIT
  license_file: LICENSE
  summary: A module wrapper for os.path
  description: |
    path.py implements a path objects as first-class entities, allowing common
    operations on files to be invoked on those path objects directly.
  doc_url: https://pathpy.readthedocs.io/en/latest/
  doc_source_url: https://github.com/jaraco/path.py/blob/master/docs/index.rst
  dev_url: https://github.com/jaraco/path.py

extra:
  recipe-maintainers:
    - jakirkham
    - nehaljwani
